<a href="https://colab.research.google.com/github/sdw1621/python_exercise/blob/main/%EC%98%88%EC%A0%9C_%EC%A4%91%EC%8B%AC_%ED%8C%8C%EC%9D%B4%EC%8D%AC_%EC%9E%85%EB%AC%B8_CH13_Numpy_%EB%8D%B0%EC%9D%B4%ED%84%B0_%EB%B6%84%EC%84%9D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###**예제 13-1. ndarray 객체 생성하기**

In [1]:
import numpy as np

data = np.array([1,2,3,4])
print(data)
print(type(data))
print(data.dtype)

[1 2 3 4]
<class 'numpy.ndarray'>
int64


###**예제 13-2. 2차원 배열 객체 생성하기**

In [2]:
import numpy as np

data = np.random.randn(2,3)
print(data)
print(data.shape)
print(data.dtype)

[[-0.63936555  0.77031008 -0.33449687]
 [-1.36955876 -2.41843469 -0.14488601]]
(2, 3)
float64


###**예제 13-3. ndarray 객체 0으로 초기화하기**

In [6]:
import numpy as np

data1 = np.zeros(10)
print(data1)
print(data1.dtype)

data2 = np.zeros((2,3))
print(data2)

data3 = np.zeros((2,3), dtype=np.int32)
print(data3)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
float64
[[0. 0. 0.]
 [0. 0. 0.]]
[[0 0 0]
 [0 0 0]]


###**예제 13-4. ndarray 객체 1으로 초기화하기**

In [8]:
import numpy as np

data1 = np.ones(8)
print(data1)

data2 = np.ones((3,4), dtype=np.int32)
print(data2)

[1. 1. 1. 1. 1. 1. 1. 1.]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


###**예제 13-5. Numpy의 arange() 메소드**

In [9]:
import numpy as np

data = np.arange(10,121,10)
print(data)
print(data[2])
print(data[5:8])

[ 10  20  30  40  50  60  70  80  90 100 110 120]
30
[60 70 80]


In [10]:
data[7:10] = 800
print(data)

[ 10  20  30  40  50  60  70 800 800 800 110 120]


In [12]:
data2 = data.reshape(2,6)
print(data2)

[[ 10  20  30  40  50  60]
 [ 70 800 800 800 110 120]]


###**예제 13-6. 2차원 배열의 요소 추출**

In [24]:
import numpy as np

data = np.array([[1,2,3,4,5],
                [6,7,8,9,10],
                [11,12,13,14,15]])

print(data, "\n")

print(data[2][3], "\n")
print(data[0][1:], "\n")
print(data[0], "\n")
print(data[1,2])

data[1] = 100
print(data)

data[:] = 200
print(data)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]] 

14 

[2 3 4 5] 

[1 2 3 4 5] 

8
[[  1   2   3   4   5]
 [100 100 100 100 100]
 [ 11  12  13  14  15]]
[[200 200 200 200 200]
 [200 200 200 200 200]
 [200 200 200 200 200]]


###**예제 13-7. numpy 배열의 산술 연산**

In [29]:
import numpy as np

a = np.array([
              [10, 7, -8, 2],
              [-2,2,8,3],
              [6,-8,-5,3]
              ])

b = a * 2
print(b)

c = a*a
print(c)

print(a > b)

[[ 20  14 -16   4]
 [ -4   4  16   6]
 [ 12 -16 -10   6]]
[[100  49  64   4]
 [  4   4  64   9]
 [ 36  64  25   9]]
[[False False  True False]
 [ True False False False]
 [False  True  True False]]


###**예제 13-8. 배열의 합계, 평균, 최댓값, 최솟값 구하기**

In [31]:
import numpy as np

data = np.array([
                 [80, 78, 90, 93],
                 [65, 87, 88, 75],
                 [98,100, 68, 80]
                 ])

print(data.sum())
print(data.mean())
print(data.max())
print(data.min())
print()

print(data.max(axis=0))
print(data.max(axis=1))
print()

index1 = np.argmax(data, axis=0)
index2 = np.argmax(data, axis=1)
print(index1, index2)

1002
83.5
100
65

[ 98 100  90  93]
[ 93  88 100]

[2 2 0 0] [3 2 1]


###**예제 13-9. 배열에 조건식 사용**

In [34]:
 import numpy as np

 data = np.random.randn(3,4)
 print(data)

 print(data > 0)

 total = (data < 0).sum()
 print(total)

 data2 = np.where(data > 0, 1, -1)
 print(data2)

 data3 = np.where(data < 0, 5, data)
 print(data3)

[[ 2.21260386  0.20525479 -0.14532124  0.96909544]
 [ 0.11084623  0.58616335  0.59544211  1.59058292]
 [ 1.20168454 -0.37364397 -0.63651558  0.94199104]]
[[ True  True False  True]
 [ True  True  True  True]
 [ True False False  True]]
3
[[ 1  1 -1  1]
 [ 1  1  1  1]
 [ 1 -1 -1  1]]
[[2.21260386 0.20525479 5.         0.96909544]
 [0.11084623 0.58616335 0.59544211 1.59058292]
 [1.20168454 5.         5.         0.94199104]]


###**예제 13-10. 배열에 요소 정렬**

In [37]:
import numpy as np

data = np.array([
                 [13, 22, 17, 2],
                 [-2, 20, 8, 3],
                 [-16, 10, -5, 33],
                 ])

data.sort(0)
print(data)
print()

data.sort(1)
print(data)

[[-16  10  -5   2]
 [ -2  20   8   3]
 [ 13  22  17  33]]

[[-16  -5   2  10]
 [ -2   3   8  20]
 [ 13  17  22  33]]


###**예제 13-11. 배열에 열과 행 삽입**

In [42]:
import numpy as np

a = np.arange(10)
print(a)

b = np.insert(a, 3, 10)
print(b)

x = np.array([[1,1,1],[2,2,2],[3,3,3]])
print(x)
print()

y = np.insert(x, 1, 10, axis=0)
print(y)

y = np.insert(x, 1, 10, axis=1)
print(y)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2 10  3  4  5  6  7  8  9]
[[1 1 1]
 [2 2 2]
 [3 3 3]]

[[ 1  1  1]
 [10 10 10]
 [ 2  2  2]
 [ 3  3  3]]
[[ 1 10  1  1]
 [ 2 10  2  2]
 [ 3 10  3  3]]
